### ISSUE TITLE
Document how to work on an android component inside an application

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/shared-docs#57]
Very often is is a good workflow to work on a component while you have embedded that component in an end user application.

For example say you are making UI changes in the toolbar. It is convenient to check out both Focus and Android-Components and see your changes in the toolbar component reflect when you run and debug Focus. Without having to use them as separate projects and depend on jar dependencies.

If this is possible, let's document how to set this up.

**Comment by st3fan** [comment]
I bet @pocmo has been working this way?

**Comment by mcomella** [comment]
Documented here: https://mozilla-mobile.github.io/android-components/contributing/testing-components-inside-app
