### ISSUE TITLE
Provide configuration info for building android-components

### ISSUE THREAD

**Issue by espertus** [mozilla-mobile/shared-docs#85]
@jonalmeida and others helped me build android-components in Android Studio.

My first mistake, which was quickly found, was that I opened, rather than imported, the project after cloning it.

My second mistake, which took a while to discover, was that building in Android Studio required setting the environment variable `JAVA_HOME`. Since I use OS X with the default (bash) shell, this entailed creating (or adding to) `.bash_profile`:

```export JAVA_HOME="/Applications/Android Studio.app/Contents/jre/jdk/Contents/Home"```

Note that setting the variable is not needed for building at the command line.

**Comment by jonalmeida** [comment]
Thanks for filing this issue @espertus !

**Comment by mcomella** [comment]
@jonalmeida I'm afraid the issue will get lost in this repo: should we cross-file to the a-c repo so the a-c team can prioritize and work on it?

Alternatively, you're the best person to work on this @espertus because you have the context on where the docs should have been that would have helped you and what they should have said so if you have time to open a PR, that would be great too! :)

**Comment by espertus** [comment]
I volunteered to. Jon was the one who suggested I file a bug. I agree with
the policy that whoever asked for help passes along the help.

**Comment by jonalmeida** [comment]
This can happen for any of our Android Studio projects so I recommended it go here, but if you assign it to me, I'll put a PR for it this week or next.

**Comment by espertus** [comment]
Well, I could add code that, if JAVA_HOME isn't set checks the default locations for java installations by Android Studio on different OSs and gives a meaningful message if none are found. Let me know if I should try doing that or just create documentation. (I think the meaningful message would be useful in any case.)

**Comment by espertus** [comment]
This was fixed in `android-components`: https://github.com/mozilla-mobile/android-components/pull/4446
